services:
  irc-msg-for-revuo:
    build: .
    restart: no
    volumes:
      - ./config.py:/app/config.py
      - ./save.pickle:/app/save.pickle
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "www.revuo-xmr.com:host-gateway"
      - "revuo-xmr.com:host-gateway"

  go-nostrss:
    image: ghcr.io/0ceanslim/go-nostrss:latest
    volumes:
      - ./nostr-config:/config/
    extra_hosts:
      - "www.revuo-xmr.com:host-gateway"
      - "revuo-xmr.com:host-gateway"

